var myName = "Shayan";
var age = 18;
var city = "Karachi";
var loan = "20$";
var car = 'Bugatti';
console.log("My name is == 'Shayan'? I predict true");
console.log(myName == 'Shayan');
console.log("My age is == 18? I predict true");
console.log(age == 18);
console.log("I live in == 'Karachi'? I predict true");
console.log(city == 'Karachi');
console.log("You have loan == '20$'? I predict true");
console.log(loan == '20$');
console.log("Is car == 'Bugatti'? I predict True.");
console.log(car == 'Bugatti');
console.log("My name is == 'Ahmed'? I predict true");
console.log(myName == 'Ahmed');
console.log("My age is == 19? I predict true");
console.log(age == 19);
console.log("I live in == 'Lahore'? I predict true");
console.log(city == 'Lahore');
console.log("You have loan == '30$'? I predict true");
console.log(loan == '30$');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
